# 
# DCE Naming Services for Solaris
#
# Paul Henson <henson@acm.org>
#
# Copyright (c) 1997-2000 Paul Henson -- see COPYRIGHT file for details
#

all: getpwnam getspnam getpwuid getpwent getgrnam getgrgid getgrent

clean:
	@rm -f getpwnam getspnam getpwuid getpwent getgrnam getgrgid getgrent *~
