# 
# DCE Naming Services for Solaris
#
# Paul Henson <henson@acm.org>
#
# Copyright (c) 1997 Paul Henson -- see COPYRIGHT file for details
#

all: getpwnam getpwuid getpwent getgrnam getgrgid getgrent

clean:
	@rm -f getpwnam getpwuid getpwent getgrnam getgrgid getgrent *~
