# 
# DCE Naming Services for Solaris
#
# Paul Henson <henson@acm.org>
#
# Copyright (c) 1997 Paul Henson -- see COPYRIGHT file for details
#

all: pwbynam pwbyuid grbynam grbygid

clean:
	@rm -f pwbynam pwbyuid grbynam grbygid *~
